# Use a imagem oficial do Python como base
FROM python:3.12.6

# Defina o diretório de trabalho no contêiner
WORKDIR /app

# Copie o script client.py para o diretório de trabalho
COPY . .

# Comando para executar o script Python
# CMD ["python3", "client.py"]