version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: airport-server
    ports:
      - "5050:5050"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: airport-client
    depends_on:
      - server
    stdin_open: true